apiVersion: apps/v1
kind: Deployment
metadata:
  name: uniflow-deployment
spec:
  replicas: 3  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: uniflow
  template:
    metadata:
      labels:
        app: uniflow
    spec:
      containers:
      - name: uniflow-container
        image: your-docker-image:latest
        ports:
        - containerPort: 80  # Adjust the port as needed
---
apiVersion: v1
kind: Service
metadata:
  name: uniflow-service
spec:
  selector:
    app: uniflow
  ports:
    - protocol: TCP
      port: 80  # Adjust the port as needed
      targetPort: 80  # Adjust the target port as needed
---

